version: '3.3'

services:
  nginx:
    depends_on:
      - nuxt
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx/conf.d/dev:/etc/nginx/conf.d
      # Для красоты...
      - ./nginx/json:/usr/share/nginx/json
      #  Монтируем папку со статикой
      - ./nuxt/static:/var/www/static
    logging:
      driver: none
    restart: no

  postgres:
    image: postgres:12-alpine
    command: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: no

  nuxt:
    tty: true
    tmpfs: /tmp
    build: 
      context: ./nuxt
      target: development
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    expose:
      - '3000'
    ports:
      - '24678:24678'
    volumes:
      - ./nuxt:/web
    restart: no

  redis:
    image: redis:alpine
    expose:
      - '6379'
    restart: no
    logging:
      driver: none

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@vverh.digital
      PGADMIN_DEFAULT_PASSWORD: BwZQXUxijMcw
    ports:
    - '5050:80'  # ← ОБЯЗАТЕЛЬНО ДОБАВЬ ЭТО
    restart: no