version: '3.3'

services:
  nginx:
    depends_on:
      - nuxt
      - pgadmin
    image: nginx:latest
    # ports:
    #   - '80:80'
    expose:
      - '80'
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx/conf.d/prod:/etc/nginx/conf.d
      # Для красоты...
      - ./nginx/json:/usr/share/nginx/json
      #  Монтируем папку со статикой
      - ./nuxt/static:/var/www/static
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    restart: always

  caddy:
    image: caddy:alpine
    depends_on:
      - nginx
    ports:
     - '80:80'
     - '443:443'
    volumes:
      - ./caddy/caddy-data:/data/caddy
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    restart: always

  postgres:
    image: postgres:12-alpine
    command: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always

  nuxt:
    build: 
      context: ./nuxt
      target: production
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    # Так же пробрасываем порт на котором висит приложение
    expose:
      - '3000'
    volumes:
      #  Монтируем папку со статикой
      - ./nuxt/static:/web/static
    restart: always

  # Для кеша
  redis:
    image: redis:alpine
    expose:
      - '6379'
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@vverh.digital
      PGADMIN_DEFAULT_PASSWORD: BwZQXUxijMcw
    expose:
      - '5050'
    restart: always